### ISSUE TITLE
漫画waifu2x转换卡在“开始转换”

### ISSUE THREAD

**Issue by StackExplode** [tonquer/ehentai-qt#10]
### 操作系统（如MacOS 10.15）
>
Windows10 1803

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
电信宽带+梯子工作正常

### 问题描述（简要描述发生的问题）
>

Waifu2x看漫画时工作不正常，一直卡在“开始转换”
### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
任意漫画点进去都是这样
![image](https://user-images.githubusercontent.com/19866685/155517851-f4329271-c08d-4134-a24c-d492a1b26f3e.png)
我的设置如图：
![image](https://user-images.githubusercontent.com/19866685/155517974-7e7ac737-bda9-4411-b289-71e7cf2fa5fa.png)

### 日志提交（问题截图或者日志，日志在logs目录）
>
使用Debug模式看图每翻一页输出如下错误：
2022-02-24 19:43:22,701 - task_download.py[line:222] - ERROR: 'TaskWaifu2x' object has no attribute 'AddConvertTask'
Traceback (most recent call last):
  File "task\task_download.py", line 218, in HandlerTask
  File "view\read\read_view.py", line 295, in CompleteDownloadPic
  File "view\read\read_view.py", line 239, in CheckLoadPicture
  File "view\read\read_view.py", line 457, in AddCovertData
  File "task\qt_task.py", line 84, in AddConvertTask
AttributeError: 'TaskWaifu2x' object has no attribute 'AddConvertTask'

**Comment by tonquer** [comment]
V1.0.6已修复

**Comment by StackExplode** [comment]
感谢更新，不过更新后好像出现新的问题了：
1. http代理正常，但用到socks5就提示“网络错误，请检查代理设置”，无论是否启用DoH均无改善。麻烦看看我设置的Uri格式对不对：
![image](https://user-images.githubusercontent.com/19866685/156963123-9be0b0aa-782c-48ef-9d62-289a77a362c8.png)

2. 在表站模式下，一切正常；切换里站后搜索的缩略图都正常，但点进去看大图时提示“错误”，当时的控制台输出：
![image](https://user-images.githubusercontent.com/19866685/156962806-3a9971ef-e50b-4bb1-a04b-2b830965b186.png)
*在搜索时都是请求的是exhentai网站，而点进阅读后在请求e-hentai，我猜测是不是这个原因*

**Comment by tonquer** [comment]
1、sock代理格式去掉socks5://
2、你打开控制台调到INFO，复现一遍，我看看错误

**Comment by StackExplode** [comment]
1. 去掉了socks5://似乎也没用，从我用的梯子的log上看，它在请求一些ip地址而不是域名(在http代理下是正常的)，如下图
![image](https://user-images.githubusercontent.com/19866685/156970246-8b11f7ec-11a2-4a5a-a352-e633dd43a3c7.png)
*图1 sock5代理登录时在请求一些ip而不是域名*
![image](https://user-images.githubusercontent.com/19866685/156970308-c6e2631e-c2a3-4717-9bf0-5ce5148d7f96.png)
*图2 http代理模式下登录正常，请求的域名看上去也挺对*
梯子换过N国家的各节点没用，软件换过两个没用，DNS也换过好几个了8.8.8.8、168.126.63.1没用，flushdns也没用。。。但只要切到http代理就好了，这是我的个例吗？
2. 以下是info页面输出日志：
![image](https://user-images.githubusercontent.com/19866685/156970084-c886bbad-21a5-4699-bb0c-a5da7cf2c5c8.png)

**Comment by tonquer** [comment]
修复了
https://github.com/tonquer/ehentai-qt/releases/tag/v1.0.6.1
