### ISSUE TITLE
打不开程序

### ISSUE THREAD

**Issue by shibuyameltdown** [tonquer/ehentai-qt#13]
### 操作系统（如MacOS 10.15）
>win11

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信宽带

### 问题描述（简要描述发生的问题）
>点start.exe以后鼠标转两下就没了

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在logs目录）
[>](url)

**Comment by shibuyameltdown** [comment]
![Uploading QQ图片20220320195204.png…]()

**Comment by shibuyameltdown** [comment]
![QQ图片20220320195204](https://user-images.githubusercontent.com/78797438/159160960-a63925e5-a86e-4580-b657-dbc59f1b981d.png)

**Comment by tonquer** [comment]
不能有中文路径哈

**Comment by shibuyameltdown** [comment]
> 不能有中文路径哈

ok
