### ISSUE TITLE
如何通过cookie登录

### ISSUE THREAD

**Issue by xmhwws** [tonquer/ehentai-qt#14]
### 操作系统（如MacOS 10.15）
>win11

### 问题描述（简要描述发生的问题）
>无法通过cookie登录

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>通过浏览器F12抓包,把得到的cookie复制粘贴,无法登录

### 日志提交（问题截图或者日志，日志在logs目录）
>![image](https://user-images.githubusercontent.com/42903751/159162392-37696a85-5c72-4ff8-a825-adb3dddc3e7e.png)

**Comment by tonquer** [comment]
![image](https://user-images.githubusercontent.com/22116659/159164054-89ae16c3-cc71-4779-800b-e3cbdf017801.png)
![image](https://user-images.githubusercontent.com/22116659/159164080-1e5eed5c-bb07-4079-9ea2-9bbc79f0c8be.png)

这样的格式

**Comment by xmhwws** [comment]
主题界面为黑色时 ,登录界面字体提示直接没了

<img width="363" alt="2022-03-20_22-08-38" src="https://user-images.githubusercontent.com/42903751/159166499-24ce063e-1ad8-4c17-97e6-9fdc21266648.png">

**Comment by tonquer** [comment]
> 主题界面为黑色时 ,登录界面字体提示直接没了
> 
> <img alt="2022-03-20_22-08-38" width="363" src="https://user-images.githubusercontent.com/42903751/159166499-24ce063e-1ad8-4c17-97e6-9fdc21266648.png">

了解了，后续修复
