### ISSUE TITLE
可以加一个无网络时的本地播放功能吗

### ISSUE THREAD

**Issue by OBraveNewWorld** [tonquer/ehentai-qt#20]
这个即时waifu2x功能真的很好，但现在似乎还无法作为一个本地漫画阅读器？
哪怕把e站下载的漫画按照 ehentai/commies/e站一样的漫画名/default/xxx.jpg 的格式在本地手动加入，打开同名漫画的时候还是很会从e站上重新下载的样子。
直接用自带的下载，大概下50本左右就会被ban ip了。

**Comment by tonquer** [comment]
v1.0.8已支持离线模式
