### ISSUE TITLE
下载单张图片

### ISSUE THREAD

**Issue by Inkshow** [tonquer/ehentai-qt#22]
在浏览时增加快捷键或鼠标操作来下单张图片。please

**Comment by tonquer** [comment]
你指的是复制到剪贴板吗

**Comment by Inkshow** [comment]
> 你指的是复制到剪贴板吗

下载并保存文件。
比如在浏览时右键出来的选项中可以添加一个“另存为”
![image](https://user-images.githubusercontent.com/79002121/174431834-6c1e28d7-3064-4b28-aedb-a9fc5e88c1d1.png)
