### ISSUE TITLE
MAC OS latest version 打开提示app已损坏将其移到废纸篓，重新下载后仍然重现

### ISSUE THREAD

**Issue by Kalengor** [tonquer/ehentai-qt#23]
### 操作系统（如MacOS 10.15）
>

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在logs目录）
>

**Comment by tonquer** [comment]
https://github.com/tonquer/picacg-qt/issues/120

**Comment by tonquer** [comment]
下版本尝试解决

**Comment by tonquer** [comment]
v1.0.8已解决该问题
