### ISSUE TITLE
不能点最上面的标签，就是那些“游戏CG”艺术CG“，点了会报错

### ISSUE THREAD

**Issue by 2023899320** [tonquer/ehentai-qt#27]
### 操作系统（如MacOS 10.15）
>

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在logs目录）
>Traceback (most recent call last):
  File "view\search\search_view.py", line 44, in ClickKeywordListItem
AttributeError: 'SearchView' object has no attribute 'autorList'

**Comment by msyzzm** [comment]
I have same problem

**Comment by tonquer** [comment]
下个版本修复

**Comment by tonquer** [comment]
v1.0.8已解决该问题
