### ISSUE TITLE
“下载速度”处显示“出错了”

### ISSUE THREAD

**Issue by scut-zigan** [tonquer/ehentai-qt#28]
### 操作系统（如MacOS 10.15）
>win10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>“下载速度”处显示“出错了”

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>下载漫画经常出现

### 日志提交（问题截图或者日志，日志在logs目录）
>
![image](https://user-images.githubusercontent.com/111228431/184535490-a30b94b4-35af-42b7-86be-3d8a886c0f7b.png)

**Comment by tonquer** [comment]
可能是爬的频繁了，后续加个失败后自动重新下载

**Comment by tonquer** [comment]
v1.0.8已解决该问题
