### ISSUE TITLE
下载路径优化

### ISSUE THREAD

**Issue by Yuhyeong** [tonquer/ehentai-qt#29]
### 功能描述（请清晰的、详细的描述你想要的功能）
> eh中的图集都是全本图集，若下载后进入图集名称文件夹后，若能直接浏览图片体验感会更好
>即 目录结构若为如下，则在后期浏览本地图片时更简洁，无需递归进入子目录
--commies
------default
---------(C78)xxxxxxxxxx
---------(C84)xxxxxxxxxx
------waifu2x
---------(C78)xxxxxxxxxx
---------(C84)xxxxxxxxxx

### 附加信息（其他的与功能相关的附加信息）
> 原版目录
--commies
---------(C78)xxxxxxxxxx
------default
------waifu2x
---------(C84)xxxxxxxxxx
------default
------waifu2x
### 效果演示（可以提供可借鉴的图片）
>期望目录树如第一栏所示

**Comment by Yuhyeong** [comment]
若是能将大佬这一系列的软件都设置成”若全本，则不设置子目录“就更好了

**Comment by tonquer** [comment]
v1.0.8设置一支持
