### ISSUE TITLE
希望可以多选任务之后，右键菜单中出现“开始下载”

### ISSUE THREAD

**Issue by daivem** [tonquer/ehentai-qt#32]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 希望可以多选任务之后，右键菜单中出现“开始下载”，现在多个任务的时候，需要一个一个点开始。（有时任务大多，不适用“全部开始”）

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以提供可借鉴的图片）
>

**Comment by tonquer** [comment]
v1.0.8已解决该问题
