### ISSUE TITLE
想问一下大佬为什么跳转按钮还是点了没反应呀，谢谢了

### ISSUE THREAD

**Issue by Yanxv-11** [tonquer/ehentai-qt#33]
### 操作系统（如MacOS 10.15）
>

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在logs目录）
>

**Comment by Yanxv-11** [comment]
重新下了好几次都还是没反应

**Comment by Yanxv-11** [comment]
就是这个右下角的选择页数之后跳转的按钮，重下了好几遍点了也还是没反应。我也不太清楚是哪的问题，这个跟ip代理有关系吗。




------------------&nbsp;Original message&nbsp;------------------
From: "tonquer"; 
Sendtime: Saturday, Oct 1, 2022 8:04 PM
To: "tonquer/ehentai-qt"; 
Cc: ***@***.***>; "Manual"; 
Subject: Re: [tonquer/ehentai-qt] 想问一下大佬为什么跳转按钮还是点了没反应呀，谢谢了 (Issue #33)





 
什么跳转按钮

**Comment by tonquer** [comment]
> 就是这个右下角的选择页数之后跳转的按钮，重下了好几遍点了也还是没反应。我也不太清楚是哪的问题，这个跟ip代理有关系吗。
> […](#)
> ------------------&nbsp;Original message&nbsp;------------------ From: "tonquer"; Sendtime: Saturday, Oct 1, 2022 8:04 PM To: "tonquer/ehentai-qt"; Cc: ***@***.***>; "Manual"; Subject: Re: [tonquer/ehentai-qt] 想问一下大佬为什么跳转按钮还是点了没反应呀，谢谢了 (Issue #33) 什么跳转按钮 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

是bug还没修

**Comment by tonquer** [comment]
v1.0.8已解决该问题
