### ISSUE TITLE
希望能保留网页原来的预览图功能

### ISSUE THREAD

**Issue by mx597014232** [tonquer/ehentai-qt#34]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
网页看图的时候，下方会有小的预览图。
现在软件每次都直接下载大图，这比较花时间。
有些图包看一下预览图就不会再看下去了，没必要下载大图。

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以提供可借鉴的图片）
>
![1665111525669](https://user-images.githubusercontent.com/46523652/194458665-480fea6d-d1d3-4403-b899-389c009cc76a.png)

**Comment by Yanxv-11** [comment]
兄弟 我想问一下您 这个里站的权限怎么获得啊 我三年前有一个号日本注册的三年没登陆了最近登录发现权限没了 然后两周前开vpn用美国ip又注册了一个号但是今天看权限也没下来就网页根本加载不出来（就是百度上的方法什么删除cookie呀 用gamil注册呀什么方法都试了还是不行）所以想咨询一下兄弟问问您这个里站的权限如何获得

**Comment by mx597014232** [comment]
如果你打开里站发现有个熊猫，那么删除cookie有用
如果你打开里站一片空白，那么建议更换VPN，这说明里站BAN了你当前地区的IP




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月12日(星期三) 晚上8:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tonquer/ehentai-qt] 希望能保留网页原来的预览图功能 (Issue #34)





 
兄弟 我想问一下您 这个里站的权限怎么获得啊 我三年前有一个号日本注册的三年没登陆了最近登录发现权限没了 然后两周前开vpn用美国ip又注册了一个号但是今天看权限也没下来就网页根本加载不出来（就是百度上的方法什么删除cookie呀 用gamil注册呀什么方法都试了还是不行）所以想咨询一下兄弟问问您这个里站的权限如何获得

**Comment by Yanxv-11** [comment]
我新账号还没有用手机版的试，请问我网页版的如何打开里站呢。我是先登录表站，登录账号，然后直接输入网址exhentai.org的话打不开，显示connect建立连接失败，有没有通过表站进里站的方法呢。手机版的话我之前的老账号中间显示的就是哭泣的熊猫，然后cookie的igneous显示的mystery，但是如何在手机上删除cookie呢

**Comment by tonquer** [comment]
v1.0.8已支持
