### ISSUE TITLE
搜索界面 "解析出错了" 问题

### ISSUE THREAD

**Issue by zyl1121** [tonquer/ehentai-qt#39]
### 操作系统（如MacOS 10.15）
> Windows 11 21H2

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 联通

### 问题描述（简要描述发生的问题）
> 搜索界面提示解析出错了

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 点击左边的搜索就会出现问题

### 日志提交（问题截图或者日志，日志在logs目录）
> 点击搜索中的标签时，提示
```
Traceback (most recent call last):
  File "view\search\search_view.py", line 44, in ClickKeywordListItem
AttributeError: 'SearchView' object has no attribute 'autorList'
```

**Comment by yisallu** [comment]
同样的问题

**Comment by tonquer** [comment]
首页改版了和里站一样，正在改

**Comment by tonquer** [comment]
v1.0.8已解决该问题
