### ISSUE TITLE
按tag搜索之后，重新在历史记录选择时会多出来的转义字符

### ISSUE THREAD

**Issue by daivem** [tonquer/ehentai-qt#41]
### 操作系统（如MacOS 10.15）
> win11

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 电信

### 问题描述（简要描述发生的问题）
>
譬如搜索了
language:"chinese$"

重新在历史中选择的时候会变成
language:""chinese$"$"

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 上面已经写了

### 日志提交（问题截图或者日志，日志在logs目录）
> 感觉不需要

**Comment by tonquer** [comment]
请更新v1.1.0版本
