### ISSUE TITLE
漫画详情页点击预览后没有图片缩略图显示

### ISSUE THREAD

**Issue by lingos33** [tonquer/ehentai-qt#42]
### 操作系统（Windows 10）
>

### 网络环境（海外wifi）
>

### 问题描述
>
<img width="713" alt="Snipaste_2022-11-28_14-04-17" src="https://user-images.githubusercontent.com/104963692/204359979-2a8aa4d1-9633-44d0-abdb-b4b1c05d1fc9.png">

**Comment by tonquer** [comment]
是否已经登录了

**Comment by lingos33** [comment]
> 是否已经登录了

嗯，已经登录了
