### ISSUE TITLE
搜索页页面跳转相关功能添加

### ISSUE THREAD

**Issue by lingos33** [tonquer/ehentai-qt#43]
### 功能描述（我在下拉相关搜索页到底端的时候，界面总是会自动帮我加载出下一页内容来，想请问这个功能可以实现“设置内关闭/开启”吗？我想要手动点击下一页来加载后边的内容。另外，希望能够增加数字页码栏，通过点击数字来实现页面跳转。谢谢作者！）

**Comment by tonquer** [comment]
ehentai已经取消跳页的功能，只有下一页和尾页

**Comment by lingos33** [comment]
好的，还是谢谢你！
