### ISSUE TITLE
为啥 ehentai 项目里面需要那么多文件支持？而另外两个则不需要呢？求解，谢谢、

### ISSUE THREAD

**Issue by matocool** [tonquer/ehentai-qt#50]
为啥 ehentai 项目里面需要那么多文件支持？而另外两个则不需要呢？求解，谢谢、

**Comment by tonquer** [comment]
因为带了浏览器 单文件中文用户名无法打开。
后续会去掉浏览器，去掉帐号登陆只保留cookie登陆，才能单文件

**Comment by matocool** [comment]
> 因为带了浏览器 单文件中文用户名无法打开。 后续会去掉浏览器，去掉帐号登陆只保留cookie登陆，才能单文件

原来如此，谢谢作者。
