### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by pinkypigeon** [tonquer/ehentai-qt#7]
### 操作系统（如MacOS 10.15）
>
win10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>无关

### 问题描述（简要描述发生的问题）
>点击start没有反应

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>只是没有反应

### 日志提交（问题截图或者日志，日志在logs目录）
>start. py[line:59] - WARNING: init scene ratio: 1.25

QLayout: Attempting to add QLayout to QWidget LineEditHelp" , which already has a layout Could not find QtWebEngineProcess. exe

**Comment by tonquer** [comment]
你的windows是中文用户名吗

**Comment by pinkypigeon** [comment]
不是中文，路径也没有中文

**Comment by tonquer** [comment]
从新换了个打包方式，
可以[下载试试](https://github.com/tonquer/ehentai-qt/actions/runs/1704310160)

**Comment by PickMeltryllis** [comment]
> v1.0.5发布，已修复这个问题

大佬，我1.0.4版本能启动，到了1.0.5就不能启动了，跟楼主一样。
