### ISSUE TITLE
是不是寄了？

### ISSUE THREAD

**Issue by DSSM1031** [tonquer/ehentai-qt#9]
### 操作系统（如MacOS 10.15）
>win10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信宽带 有挂梯子

### 问题描述（简要描述发生的问题）
>看不到任何漫画

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>就是 看不到，已经登陆了有权限的账号（cookie登录），切换表里显示成功，但是看不到任何漫画

### 日志提交（问题截图或者日志，日志在logs目录）
>
![image](https://user-images.githubusercontent.com/44673574/154971260-15d616ef-6b05-4294-9686-6ef53eb1b1fa.png)

**Comment by tonquer** [comment]
有空我在试试

**Comment by tonquer** [comment]
v1.0.6尝试修复了这个问题
